language: ruby

gemfile:
  - gemfiles/rails4.gemfile

before_script:
  - cp ./spec/test_app/config/database.yml.travis ./spec/test_app/config/database.yml
  - bundle exec rake app:db:migrate RAILS_ENV=test
    #- cd spec/test_app
    #- bundle exec rake spec_score_api:install:migrations
    #- bundle exec rake db:migrate RAILS_ENV=test
    # cd ../../

rvm:
  - '2.0.0'
    #  - '1.9.3'
    # - '2.1.1'


