language: ruby

gemfile:
  - gemfiles/rails4.gemfile

before_script:
  - cp spec/test_app/config/database.yml.travis spec/test_app/config/database.yml
  - ci/setup.sh

rvm:
  - '1.9.3'
  - '2.0.0'
  - '2.1.1'


